[phases.setup]
cmds = [
    "apt-get update",
    "curl -fsSL https://deb.nodesource.com/setup_18.x | bash -",
    "apt-get install -y nodejs"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step needed for Node.js backend'"]

[start]
cmd = "npm start"

[build.environment]
NODE_ENV = "production"

[plan]
version = 1